### ISSUE TITLE
Support selective forwarding

### ISSUE THREAD

**Issue by carstenbaumhoegger** [maticzav/graphql-middleware-forward-binding#1]
hey @maticzav !
I just found this project and I really like it, because it solves one big pain point I have which is not having the auto-generated resolvers from prisma available at my `graphql-yoga` endpoint.
One problem I have is: I need the `login`, `signup`, etc. mutations from `graphql-yoga`, to get a working environment. 
Could you try to implement some sort of "selective" forwarding, where not all mutations get forwarded?
Maybe you already implemented this and I missed the feature?
Thanks for the great work!

**Comment by maticzav** [comment]
hey @carstenbaumhoegger! 

thank you for such nice feedback! I have unfortunately not. I was thinking about it but couldn't find a meaningful API solution. 

This package is based on `forwardTo` property which is exposed by `graphql-binding` as well as `prisma-binding`. It's extremely easy to use this one as well. You can read more about it here https://github.com/prismagraphql/prisma-binding/blob/master/README.md#forwardto .

I would love to improve this package; therefore, if you have any idea of how we could make your case work with a general API I would be more than happy to hear it! 

I hope this helps you solve your case. 🙂

**Comment by maticzav** [comment]
@carstenbaumhoegger just added support for this, check out 30bfb4a! 🎉

**Comment by carstenbaumhoegger** [comment]
hey @maticzav !
Sorry for my late response.

The changes you made are great! 🎉 

I would have another usage for this selective forwarding but with some kind of "blacklisting". So instead of providing all queries and mutations that should be forwarded, I'd like to provide all, that should NOT be forwarded and handled by `graphql-yoga` 😄 

Do you know a solution for this problem?

Thanks in advance
Carsten

**Comment by maticzav** [comment]
Hey man, sure thing! I am glad you like it 🍻 I think the easiest way to achieve blacklisting like feature is by copying `Query` and `Mutation` types and just removing the fields you don’t need. 

I also think that we don't need explicit functionality for blacklisting because of this since it wouldn't make sense, at least that's what I think 😄

You probably know how the rest of the implementation should work 🎉
