### ISSUE TITLE
How can I forward only subfields?

### ISSUE THREAD

**Issue by marktani** [maticzav/graphql-middleware-forward-binding#2]
The example in the `README` uses this:

`const bindingForwardMiddleware = forward('Query', 'Mutation')('db')`

What if I only want to forward specific queries? Does the following work?

`const bindingForwardMiddleware = forward('Query.myQuery', Query.anotherQuery')('db')`

**Comment by maticzav** [comment]
@marktani 30bfb4a love the API, just added it!
